name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        
    - name: Make gradlew executable
      run: chmod +x ${{ github.workspace }}/Server/gradlew

    - name: Build with Gradle
      run: 
        cd "${{ github.workspace }}/Server"   
        ./gradlew build --no-daemon
