name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        
    - name: Make gradlew executable
      run: chmod +x ${{ github.workspace }}/Server/gradlew

    - name: Build with Gradle
      run: cd ${{ github.workspace }}/Server && ./gradlew build --no-daemon

    - name: Log in to Quay.io
      run: echo ${{ secrets.PASS_QUAYIO }} | docker login quay.io -u ${{ secrets.USER_QUAYIO }} --password-stdin
        
    - name: Build Docker image
      run: cd ${{ github.workspace }}/Server && docker build -t quay.io/tqduy025_dev/tshine:latest .

    - name: Push Docker image to Quay.io
      run: docker push quay.io/tqduy025_dev/tshine:latest
